//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadaTech_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetImage
    {
        public long AssetImgId { get; set; }
        public Nullable<long> AssetId { get; set; }
        public string AssetImage1 { get; set; }
        public bool IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual AssetMaster AssetMaster { get; set; }
    }
}
