//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadaTech_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMaster
    {
        public int ConfigId { get; set; }
        public string ConfigKey { get; set; }
        public string ConfigValues { get; set; }
    }
}
