//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadaTech.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetMaster()
        {
            this.AssetImages = new HashSet<AssetImage>();
            this.AssetTagDetails = new HashSet<AssetTagDetail>();
        }
    
        public long AssetId { get; set; }
        public long PartId { get; set; }
        public string AssetName { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Notes { get; set; }
        public string AssetImage { get; set; }
        public bool IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsMoveable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetImage> AssetImages { get; set; }
        public virtual PartMaster PartMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetTagDetail> AssetTagDetails { get; set; }
    }
}
