//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadaTech.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> UserType { get; set; }
        public bool IsDelete { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string DeviceID { get; set; }
    
        public virtual UserGroupMaster UserGroupMaster { get; set; }
    }
}
